<html>
<head>
 <title>GoFood</title>
</head>
<body>
<table border="1" width="300">
 <caption>Go Food Menu</caption>
 <thead>
  <tr>
   <td>No</td>
   <td>Nama Makanan</td>
   <td>Harga</td>
   <td>Pesan</td>
  </tr>
 </thead>
 <tbody>
  <tr>
   <td>1</td>
   <td>Bakso</td>
   <td>20000</td>
   <td><input type="checkbox" name="chk1"></td>
  </tr>
  <tr>
   <td>2</td>
   <td>Daging</td>
   <td>50000</td>
   <td><input type="checkbox" name="chk2"></td>
  </tr>
  <tr>
   <td>3</td>
   <td>Krupuk</td>
   <td>5000</td>
   <td><input type="checkbox" name="chk3"></td>
  </tr>
  <tr>
   <td>4</td>
   <td>Mie Ayam</td>
   <td>13000</td>
   <td><input type="checkbox" name="chk4"></td>
  </tr>
 </tbody>
</table>
<br><input type="submit" name="sbmt" value="Masukkan">
</body>
</html>